language: node_js
sudo: false
cache:
  directories:
  - node_modules
matrix:
  include:
  - node_js: '0.10'
  - node_js: '0.12'
  - node_js: '4.2'
  - node_js: '5.0'
    env: npm_config_coverage=1
addons:
  code_climate:
    repo_token:
      secure: FuoC372knbZN7ZCC+zFE7KN04TFCYlz+FNB+9FozL307t1g5Vy3piOMmCXmj/Lt8WserjEZj5aczBYv8fPR6UrwHSRPFbBsnmvOjgHsZc52k7k/qnZb6CnKDBwYMY5C3XKVAtgIS0llr7ofYexfwrlEWdm+Z3kwjkUblmspwZCE=
after_success: |
  if [ -n "$npm_config_coverage" ]; then
    npm install -g codeclimate-test-reporter
    codeclimate-test-reporter < coverage/lcov.info
  fi
deploy:
  provider: npm
  email: me@samcday.com.au
  api_key:
    secure: ggWdz5YIK63cteRxpqvDkwSydI5hOcdKc8zpJMd+Sj4uvl1XMeLzVSwOkfMZxg7f3gTkVdzZczSquNoIiQp/mRRszPS0y/PSWBVxxp77Qkr8CxRCK97VscfvXcbmaCrrxk1FW/uzHLG/dkQ/PJdoiRdrw6m2c/u5EmRAr934irQ=
  on:
    tags: true
    repo: samcday/node-google-spreadsheets
    node: '5.0'
